### ISSUE TITLE
[BUG]: Failed to generate cover letter because of stringWidth function

### ISSUE THREAD

**Issue by Axedyson** [AIHawk-co/Auto_Jobs_Applier#545]
### Describe the bug

Failed to generate cover letter because a function in the utils file calls the function `getbbox` on a str. Maybe instead of a str it should be som Pillow.imageFont object?

### Expected behavior

Generate cover letter without any issues

### Actual behavior

Failed to generate cover letter due to some bug in the code

### Branch

main

### Branch name

main

### Python version

3.12.7

### LLM Used

OpenAI

### Model used

gtp-4o

### Additional context

**Output in terminal:**

```
2024-10-15 11:40:15.187 | DEBUG    | src.aihawk_easy_applier:_create_and_upload_cover_letter:524 - Generated file path for cover letter: generated_cv/Cover_Letter_1728985215.pdf
2024-10-15 11:40:15.187 | ERROR    | src.aihawk_easy_applier:_create_and_upload_cover_letter:573 - Failed to generate cover letter: 'str' object has no attribute 'getbbox'
2024-10-15 11:40:15.188 | ERROR    | src.aihawk_easy_applier:_create_and_upload_cover_letter:575 - Traceback: Traceback (most recent call last):
  File "/home/anders/Project/Auto_Jobs_Applier_AIHawk/src/aihawk_easy_applier.py", line 553, in _create_and_upload_cover_letter
    lines = split_text_by_width(cover_letter_text, "Helvetica", 12, max_width)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anders/Project/Auto_Jobs_Applier_AIHawk/src/aihawk_easy_applier.py", line 539, in split_text_by_width
    if utils.stringWidth(line, font, font_size) > max_width:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anders/Project/Auto_Jobs_Applier_AIHawk/src/utils.py", line 171, in stringWidth
    bbox = font.getbbox(text)
           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'getbbox'

2024-10-15 11:40:15.188 | ERROR    | src.aihawk_easy_applier:fill_up:337 - Failed to find form elements: 'str' object has no attribute 'getbbox'
```

**Comment by feder-cr** [comment]
@Axedyson fixed, join in our telegram group https://t.me/AIhawkCommunity
